### PR TITLE
Add home page

### LINKED ISSUE #52: User Story - Home Page
# Story Description

- As a user, I would like to have a home page that explains the apps features.

# Acceptance Criteria

- home page should list main features

### PR DESCRIPTION
**Pull request by SyedTahaA**
This pr adds a home page which highlights some of the features of the app.

resolves: #52

### CODE REVIEW

**Review by andy9775 — CHANGES_REQUESTED** [review]
Do we have rights to the images?

**Comment by SyedTahaA** [comment]
> Do we have rights to the images?

I found them on google images, I'm not sure if they are under free to use but I can cite them.

**Comment by andy9775** [comment]
> > Do we have rights to the images?
> 
> I found them on google images, I'm not sure if they are under free to use but I can cite them.

Unfortunately you can't just cite them. You need rights to use them. 

There are sites out there which have images you can use with an open licence. Unsplash gives you photographs for example.

**Comment by SyedTahaA** [comment]
> > > Do we have rights to the images?
> > 
> > 
> > I found them on google images, I'm not sure if they are under free to use but I can cite them.
> 
> Unfortunately you can't just cite them. You need rights to use them.
> 
> There are sites out there which have images you can use with an open licence. Unsplash gives you photographs for example.

fixed, I used https://www.freepik.com/. They provide free to use images as long as the author is attributed.

**Review by andy9775 — APPROVED** [review]
I would perhaps put an attribution in the README as well just to be safe.

Otherwise LGTM

**Review by stalhaali — APPROVED** [review]
LGTM

**Pull request merged**
